### ISSUE TITLE
TypeError: add_labels() got an unexpected keyword argument 'color'

### ISSUE THREAD

**Issue by paapu88** [JoOkuma/napari-segment-anything#29]
Dear Developers,
I have ubuntu linux 24.04 and did run the following:
```
 python -m venv ~/venvs/napari
source ~/venvs/napari/bin/activate
pip install pyqt5
pip install pyside2
pip install git+https://github.com/jookuma/napari-segment-anything.git
```
Now running in segment-anything directory with their dog
(from https://github.com/facebookresearch/segment-anything.git)
`napari images/dog.jpg -w napari-segment-anything 'Segment Anything'`

Shows quickly the image and then dies with the following:

> Traceback (most recent call last):
  File "/home/markus/venvs/napari/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/markus/venvs/napari/lib/python3.12/site-packages/napari/__main__.py", line 584, in main
    _run()
  File "/home/markus/venvs/napari/lib/python3.12/site-packages/napari/__main__.py", line 383, in _run
    first_dock_widget = viewer.window.add_plugin_dock_widget(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/venvs/napari/lib/python3.12/site-packages/napari/_qt/qt_main_window.py", line 1081, in add_plugin_dock_widget
    wdg = _instantiate_dock_widget(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/venvs/napari/lib/python3.12/site-packages/napari/_qt/qt_main_window.py", line 1894, in _instantiate_dock_widget
    return wdg_cls(**kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/home/markus/venvs/napari/lib/python3.12/site-packages/napari_segment_anything/_widget.py", line 71, in __init__
    self._mask_layer = self._viewer.add_labels(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/venvs/napari/lib/python3.12/site-packages/napari/utils/_proxies.py", line 194, in __call__
    return self.create(self.__wrapped__(*args, **kwargs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: add_labels() got an unexpected keyword argument 'color'
WARNING: QThread: Destroyed while thread is still running
13:20:16 : WARNING : MainThread : QThread: Destroyed while thread is still running
Aborted (core dumped)

Terveisin, Markus

**Comment by JoOkuma** [comment]
Hi, @paapu88, thanks for pointing this out.

`napari` deprecated the `color` keyword argument from `add_labels`

I currently don't have time to fix this, but I'm happy to review a PR if you have the bandwidth to fix this and update the napari version.

**Comment by paapu88** [comment]
Ok, did pull request with a fix. 
Thanks for this repo, it combines great things! 
Terveisin, Markus

**Comment by fabricesenger** [comment]
hello,
tested today and got the same error.
Any recommendation on this issue ?

Thank you,

Fabrice

**Comment by pablopriet** [comment]
Same here. 
Any luck?

**Comment by macromeer** [comment]
This is how you fix it locally for napari-segment-anything-0.1.4:

```
mamba create -y -n napari-sam -c conda-forge python=3.10
mamba activate napari-sam
python -m pip install "napari[all]"
git clone https://github.com/royerlab/napari-segment-anything.git # into a folder of your choice
```

Now you comment out line 74 in `/napari-segment-anything/src/napari_segment_anything/_widget.py`

Then 

```
cd napari-segment-anything
pip install -e .
```

Go on with `napari`and segment anything.

**Comment by fabricesenger** [comment]
Thank you! 
Will test and let you know. 
Have a nice WE, 
Fabrice 


De: "Marco Meer" ***@***.***> 
À: "royerlab/napari-segment-anything" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Vendredi 25 Avril 2025 16:15:21 
Objet: Re: [royerlab/napari-segment-anything] TypeError: add_labels() got an unexpected keyword argument 'color' (Issue #29) 

macromeer left a comment [ https://github.com/royerlab/napari-segment-anything/issues/29#issuecomment-2830557202 | (royerlab/napari-segment-anything#29) ] 


This is how you fix it: 
mamba create -y -n napari-sam -c conda-forge python=3.10
mamba activate napari-sam
python -m pip install "napari[all]"
git clone https://github.com/royerlab/napari-segment-anything.git # into a folder of your choice 


Now you comment out line 74 in ./napari-segment-anything/src/_widget.py 

Then 
cd napari-segment-anything
pip install -e . 


Now you have locally fixed the issue.

**Comment by pnaclcu** [comment]
pip uninstall -y napari

# install old version fixed this issue
pip install "napari==0.4.19" pyqt5  # 或 pyside2，随你
