### ISSUE TITLE
ValueError: Only 2D images supported. Got 3-dim image

### ISSUE THREAD

**Issue by beenoe** [JoOkuma/napari-segment-anything#7]
Traceback (most recent call last):
  File "C:\conda\envs\yolov5\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\conda\envs\yolov5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\conda\envs\yolov5\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\conda\envs\yolov5\lib\site-packages\napari\__main__.py", line 561, in main
    _run()
  File "C:\conda\envs\yolov5\lib\site-packages\napari\__main__.py", line 370, in _run
    first_dock_widget = viewer.window.add_plugin_dock_widget(
  File "C:\conda\envs\yolov5\lib\site-packages\napari\_qt\qt_main_window.py", line 717, in add_plugin_dock_widget
    wdg = _instantiate_dock_widget(
  File "C:\conda\envs\yolov5\lib\site-packages\napari\_qt\qt_main_window.py", line 1365, in _instantiate_dock_widget
    return wdg_cls(**kwargs)
  File "C:\conda\envs\yolov5\lib\site-packages\napari_segment_anything\_widget.py", line 91, in __init__
    self._model_type_widget.changed.emit(model_type)
  File "src\psygnal\_signal.py", line 927, in emit
  File "src\psygnal\_signal.py", line 974, in _run_emit_loop
psygnal._exceptions.EmitLoopError: calling <psygnal._weak_callback._WeakMethod object at 0x000001FA4574BB40> with args=('default',) caused ValueError: Only 2D images supported. Got 3-dim image..

Exited as it showed. Why is 3-dim image not supported?

**Comment by JoOkuma** [comment]
Hi @beenoe , we haven't extended the project to 3D, so it only works with grayscale or RGB 2D images for now.

**Comment by cudmore** [comment]
This is a got topic! Any chance we will have segment anything for 3D microscopy images? Like image stacks?

**Comment by JoOkuma** [comment]
@cudmore, [micro-sam](https://github.com/computational-cell-analytics/micro-sam) supports 3D images, you should give it a try.
